### PR TITLE
bugfix: fix not working connection annotation

### PR DESCRIPTION
**Pull request by devkral**
Add FOrwardRef to resolve stringified annotations

### CODE REVIEW

**Comment by bellini666** [comment]
Hey @devkral , thanks for the PR!

There's just an issue with linting. Try to run `pre-commit` on it and it should fix the issue

**Comment by devkral** [comment]
thanks for the fast answer. I was in hurry. I will fix it now

**Comment by devkral** [comment]
this PR fixes #42

**Comment by bellini666** [comment]
Ty!

**Pull request merged**
